name: flutter_oauth2
description: OAuth 2.0 implementation for Flutter / Dart
version: 0.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: ^1.9.4
  mockito: ^5.0.4
  build_runner: ^1.12.2