name: flutter_oauth2
description: OAuth 2.0 implementation for Flutter / Dart
version: 0.2.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dio: ^5.2.0

dev_dependencies:
  test: ^1.24.1
  mockito: ^5.4.1
  build_runner: ^2.4.4
