name: flutter_oauth2
description: OAuth 2.0 implementation for Flutter / Dart
version: 0.1.1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  dio: ^3.0.3

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1